runtime: python
vm: true
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 2
  
# [START env_variables]
env_variables:
    GCLOUD_PROJECT: socialmapkorea
# [END env_variables]